version: '3'
services:
  mysql:
    image: mysql:8.0
#    networks:
#      - my_network
    volumes:
      - .db/conf.d:/etc/mysql/conf.d
      - .db/data:/var/lib/mysql
      - .db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_ROOT_PASSWORD=mypassword

  product-service:
    image: materialized-view-product-service:0.0.1
#    networks:
#      - my_network
#      - kafka
#      - zookeeper
    ports:
        - "8081:8080"
    depends_on:
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mv?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=mypassword
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
      - LOGGING_TOPIC=xxxpay.logging.out.stdout

  stock-service:
    image: materialized-view-stock-service:0.0.1
    #    networks:
    #      - my_network
    #      - kafka
    #      - zookeeper
    ports:
    - "8082:8080"
    depends_on:
    - mysql
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mv?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=mypassword
    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092,kafka2:19092,kafka3:19092
    - LOGGING_TOPIC=xxxpay.logging.out.stdout

  materialized-view-service:
    image: materialized-view-materialized-view-service:0.0.1
    #    networks:
    #      - my_network
    #      - kafka
    #      - zookeeper
    ports:
    - "8083:8080"
    depends_on:
    - mysql
    environment:
    - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/mv?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
    - SPRING_DATASOURCE_USERNAME=root
    - SPRING_DATASOURCE_PASSWORD=mypassword
    - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
    - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    - KAFKA_CLUSTERS_BOOTSTRAPSERVERS=kafka:29092
    - LOGGING_TOPIC=xxxpay.logging.out.stdout

  zookeeper:
    image: 'bitnami/zookeeper:3.7.2'
    container_name: zookeeper
    ports:
    - 2181:2181
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
    - ./.data/zookeeper/data:/bitnami/zookeeper/data
    - ./.data/zookeeper/datalog:/bitnami/zookeeper/datalog
    - ./.data/zookeeper/logs:/bitnami/zookeeper/logs
  kafka1:
    image: 'bitnami/kafka:3.6.0'
    container_name: kafka1
    hostname: kafka1
    ports:
    - 19092
    - "9092:9092"
    environment:
    - KAFKA_BROKER_ID=1
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9092
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka1:19092,EXTERNAL://localhost:9092
    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
    - zookeeper
    volumes:
    - ./.data/kafka1:/bitnami/kafka/data
  kafka2:
    image: 'bitnami/kafka:3.6.0'
    container_name: kafka2
    ports:
    - 19092
    - "9093:9093"
    environment:
    - KAFKA_BROKER_ID=2
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka2:19092,EXTERNAL://localhost:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
    - zookeeper
    volumes:
    - ./.data/kafka2:/bitnami/kafka/data
  kafka3:
    image: 'bitnami/kafka:3.6.0'
    container_name: kafka3
    ports:
    - 19092
    - "9094:9094"
    environment:
    - KAFKA_BROKER_ID=3
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:19092,EXTERNAL://:9094
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka3:19092,EXTERNAL://localhost:9094
    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
    - zookeeper
    volumes:
    - ./.data/kafka3:/bitnami/kafka/data
  kafka-ui:
    image: 'provectuslabs/kafka-ui:v0.7.1'
    container_name: kafka-ui
    ports:
    - "8080:8080"
    environment:
    - KAFKA_CLUSTERS_0_NAME=local
    - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka1:19092,kafka2:19092,kafka3:19092
    depends_on:
    - zookeeper
    - kafka1
    - kafka2
    - kafka3

#networks:
#    my_network:
#        driver: bridge